spring.application.name=equipo-nuvia

server.port=8080
server.tomcat.max-http-form-post-size=10MB
server.tomcat.max-swallow-size=10MB

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/nuvia_db?useSSL=false&serverTimezone=America/Lima&allowPublicKeyRetrieval=true}
spring.datasource.username=root
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.jackson.time-zone=America/Lima
